### 服务器配置
server:
  servlet:
    context-path: /wuxiao
  port: 8082
### WUXIAO配置
project:
  captcha-open: false                         #是否开启登录验证码
  shiro:
    remember-me-timeout: 7                    #cookie记住登录信息时间，默认7天（天）
    global-session-timeout: 1800              #Session会话超时时间，默认30分钟（秒）
  upload:
    #file-path:                               #文件上传路径，默认在项目根目录upload下
    static-path: /upload/**                   #上传文件静态访问路径

### spring配置
spring:
## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.109:3306/wuxiao_dev?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456

## jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: com.pldk.common.mysql.MySQLDialectUTF8
      hibernate.format_sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #支持事务

  ## thymeleaf模板设置
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false
 
## 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
## mybatis配置
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
    
##五小项目配置
wuxiao:
  serverName: /wuxiao
  ##服务器存储地址
  slicePath: D:\\nginx\\html\\upload
  ##服务读取地址 
  webPath: http://wuxiao.pro.puluodike.cn/upload
  ##是否开启  true代表配置生效 false表示存储路径为项目根目录
  isPath: true

model:
  #带头人免冠照片 服务器存储地址
  leader-url-linux: D:\\nginx\\html\\leader\\
  #带头人免冠照片 mysql存储地址
  leader-url-mysql: http://wuxiao.pro.puluodike.cn/leader/

  #创新工作室视频地址 服务器存储地址
  studio-video-linux: D:\\nginx\\html\\studiovideo\\
  #创新工作室视频地址 mysql存储地址
  studio-video-mysql: http://wuxiao.pro.puluodike.cn/studiovideo/

  #创新工作室图片地址 服务器存储地址
  studio-img-linux: D:\\nginx\\html\\studioimg\\
  #创新工作室图片地址 mysql存储地址
  studio-img-mysql: http://wuxiao.pro.puluodike.cn/studioimg/

  #创新工作室附件地址 服务器存储地址
  studio-file-linux: D:\\nginx\\html\\studiofile\\
  #创新工作室附件地址 mysql存储地址
  studio-file-mysql: http://wuxiao.pro.puluodike.cn/studiofile/

  #创新工作室工会意见图片地址 服务器存储地址
  labor-union-linux: E:\\nginx\\html\\union\\
  #创新工作室工会意见图片地址 mysql存储地址
  labor-union-mysql: http://wuxiao.pro.puluodike.cn/union/

  #带头人附件地址  服务器存储地址
  leader-accessory-linux: D:\\nginx\\html\\leaderaccessory\\
  #带头人附件地址  mysql存储地址
  leader-accessory-mysql: http://wuxiao.pro.puluodike.cn/leaderaccessory/






  #创新计划视频地址 服务器存储地址
  creative-plan-video-linux: D:\\nginx\\html\\creative\\
  #创新计划视频地址 mysql存储地址
  creative-plan-video-mysql: http://wuxiao.pro.puluodike.cn/creative/

  #创新计划图片地址 服务器存储地址
  creative-plan-imgs-linux: D:\\nginx\\html\\creative\\
  #创新计划图片地址 mysql存储地址
  creative-plan-imgs-mysql: http://wuxiao.pro.puluodike.cn/creative/

  #创新计划附件地址 服务器存储地址
  creative-plan-files-linux: D:\\nginx\\html\\creative\\
  #创新计划附件地址 mysql存储地址
  creative-plan-files-mysql: http://wuxiao.pro.puluodike.cn/creative/

